- name: Check if Custom SELinux Module is Installed
  shell:
    cmd: semodule -l | grep caddy_selinux
  register: module_installed
  ignore_errors: true

# There should be a more idempotent way to handle this
- name: Install Custom Module
  block:
    - name: Copy TE to VM
      ansible.builtin.copy:
        src: ./files/caddy_selinux.te
        dest: /tmp/

    - name: Convert TE to SELinux Module
      ansible.builtin.shell:
        cmd: checkmodule -M -m -o /tmp/caddy_selinux.mod /tmp/caddy_selinux.te

    - name: Convert SELinux Module to PP
      ansible.builtin.shell:
        cmd: semodule_package -o /tmp/caddy_selinux.pp -m /tmp/caddy_selinux.mod

    - name: Install SELinux PP File
      ansible.builtin.shell:
        cmd: semodule -i /tmp/caddy_selinux.pp
  when: module_installed.rc == 1
